<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>

		<ApplicationIcon>icons8-organização-24.ico</ApplicationIcon>

		<!-- CONTROLE DE VERSÃO -->
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="icons8-organização-24.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
		<PackageReference Include="PdfSharp" Version="6.2.4" />
	</ItemGroup>

</Project>